:concurrency: 5
:queues:
  - [critical, 2]
  - [default, 1]
  - [low, 1]

:development:
  :concurrency: 5
:production:
  :concurrency: 20
  :queues:
    - [critical, 2]
    - [default, 1]
    - [low, 1]